```{r}
# Installing Packages
install.packages("ClusterR")
install.packages("cluster")

# Loading package
library(ClusterR)
library(cluster)

# Removing initial label of
# Species from original dataset
iris_1 <- iris[, -5]

# Fitting K-Means clustering Model
# to training dataset
set.seed(240) # Setting seed
kmeans.re <- kmeans(iris_1, centers = 3, nstart = 20)
kmeans.re

# Cluster identification for
# each observation
kmeans.re$cluster

# Confusion Matrix
cm <- table(iris$Species, kmeans.re$cluster)
cm

# Model Evaluation and visualization
# plot(iris_1[c("Sepal.Length", "Sepal.Width")])
# plot(iris_1[c("Sepal.Length", "Sepal.Width")],
#      col = kmeans.re$cluster)
plot(iris_1[c("Sepal.Length", "Sepal.Width")],
     col = kmeans.re$cluster,
     main = "K-means with 3 clusters")

## Plotiing cluster centers
kmeans.re$centers
kmeans.re$centers[, c("Sepal.Length", "Sepal.Width")]

# cex is font size, pch is symbol
points(kmeans.re$centers[, c("Sepal.Length", "Sepal.Width")],
       col = 1:3, pch = 8, cex = 3)

## Visualizing clusters
y_kmeans <- kmeans.re$cluster
clusplot(iris_1[, c("Sepal.Length", "Sepal.Width")],
         y_kmeans,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste("Cluster iris"),
         xlab = 'Sepal.Length',
         ylab = 'Sepal.Width')
```
```{r}
# install.packages("r2r")
library(r2r)
temp <- hashset()
insert(temp, 2)
temp[[4]]
```
```{r}
plot(iris_1[c("Sepal.Length", "Sepal.Width")],
     col = kmeans.re$cluster,
     main = "K-means with 3 clusters")

## Plotiing cluster centers
kmeans.re$centers
kmeans.re$centers[, c("Sepal.Length", "Sepal.Width")]

# cex is font size, pch is symbol
points(kmeans.re$centers[, c("Sepal.Length", "Sepal.Width")],
       col = 1:3, pch = 8, cex = 3)
```
```{r}
# q <- queue() # for doing DFS (Level Order Traversal)
#
# temp_NodeObj <- query(allNode_Map, as.character(-dp_num + 1))
# q <- insert(q, temp_NodeObj)
#
# while (size(q) > 0) {
#   first_NodeObj <- peek(q) # get the first element of the queue
#
#   # set the value of lamda_birth for all nodes
#   if (first_NodeObj$selfIdx == (-dp_num + 1)) {
#     first_NodeObj$lamda_birth <- (1 / first_NodeObj$distance_val)
#   }
#   else {
#     temp_parentNode <- query(allNode_Map, as.character(first_NodeObj$parentNodeIdx))
#     first_NodeObj$lamda_birth <- (1 / temp_parentNode$distance_val)
#   }
#   # 有问题
#
#   if (first_NodeObj$selfIdx < 0) { # we are only going to process internal nodes (idx<0)
#     # mark it as the potentialNoise if its nums of children is smaller than MCS
#     if (length(first_NodeObj$hasChildren) < MCS) {
#       first_NodeObj$potentialNoise <- TRUE
#       # print(first_NodeObj$selfIdx)
#     }
#
#     next_leftNodeIdx <- first_NodeObj$leftNodeIdx
#     next_leftNode <- query(allNode_Map, as.character(next_leftNodeIdx))
#     q <- insert(q, next_leftNode)
#
#     next_rightNodeIdx <- first_NodeObj$rightNodeIdx
#     next_rightNode <- query(allNode_Map, as.character(next_rightNodeIdx))
#     q <- insert(q, next_rightNode)
#   }
#
#   pop(q)
# }

```