---
title: "R Notebook"
output: html_document
---
```{r}
# install.packages("ClusterR")
# install.packages("cluster")

# Loading package
library(ClusterR)
library(cluster)
```
```{r}
# import the multishapes data from the docker
result <- system("docker exec namenode hdfs dfs -cat ./input/multishapes.csv", intern = TRUE)
writeLines(result, "./kmean/temp_multishape.csv")
multishape_data <- read.csv("./kmean/temp_multishape.csv",
                            header = TRUE,
                            colClasses = c("NULL", NA, NA, NA),
                            col.names = c("idx", "x_coordinate", "y_coordinate", "shape_class"))
```
```{r}
# subtract the xy_params,
xy_params <- multishape_data[, -3]
```
```{r}
# fit into k-mean clustering
set.seed(100) # set the seed
kmean_model <- kmeans(xy_params, centers = 6, nstart = 20) # set the nums of certoids as 3 and iterate 20 times
kmean_model
```
```{r}
# Cluster identification for
# each observation
# kmean_model$cluster
```
```{r}
# Confusion Matrix
cm <- table(multishape_data$shape_class, kmean_model$cluster)
cm
```
```{r}
# Evaluate and visualize the model
plot(xy_params[c("x_coordinate", "y_coordinate")], col = kmean_model$cluster, pch = 20, main = "K-means with 6 clusters")
```
```{r}
## Plotiing cluster centers
kmean_model$centers[, c("x_coordinate", "y_coordinate")]
```
```{r}
# # cex is font size, pch is symbol
# points(kmean_model$centers[, c("x_coordinate", "y_coordinate")],
#        col = 1:3, pch = 8, cex = 5)
```
```{r}
## Visualizing clusters
y_kmeans <- kmean_model$cluster
clusplot(xy_params[, c("x_coordinate", "y_coordinate")],
         y_kmeans,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste("Multishape Cluster"),
         xlab = 'x',
         ylab = 'y')
```
